\apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingressgateway
  namespace: cicd
spec:
  sources:
    - repoURL: 'https://istio-release.storage.googleapis.com/charts'
      targetRevision: 1.27.1
      chart: gateway
      helm:
        releaseName: ingressgateway
        valueFiles:
          - $values/istio/chart/ingressgateway.yaml
    - repoURL: 'https://github.com/beer-one/k8s-manifests.git'
      targetRevision: main
      ref: values
  destination:
    name: ''
    namespace: istio-system
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy: 
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true